name: tweet_streamer
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
  - autopep8
  - click
  - coverage
  - flake8
  - ipython
  - jedi
  - joblib
  - jupyter
  - jupyterlab
  - nb_conda
  - pylint
  - pytest
  - pytest-cov
  - requests
  - setuptools
  - sphinx
  - wheel
  - python>=3.7
  - pymongo
  - tweepy

